global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: 'aphorma-mdt'
    metrics_path: '/metrics'
    scrape_interval: 10s
    static_configs:
      - targets: ['aphorma-mdt:8000']
        labels:
          service: 'aphorma-mdt'
          environment: 'production'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']
